#ifndef IAMABUS_CONSTANTS_H
#define IAMABUS_CONSTANTS_H

#ifndef DEBOUNCE_DELAY
#define DEBOUNCE_DELAY 50
#endif

#ifndef SCREENSAVER_TIMEOUT 
#define SCREENSAVER_TIMEOUT 30000
#endif

enum Menu_Triggers {
    MENU_ACTION_IDLE,
    MENU_ACTION_SELECT_MENU,
    MENU_ACTION_NETWORK_MENU,
    MENU_ACTION_NETWORK_ENABLE,
    MENU_ACTION_NETWORK_DISABLE,
    MENU_ACTION_EXIT = 255
};

enum FSM_Triggers {
    FSM_TRIGGER_REST,
    FSM_TRIGGER_MAIN_MENU,
    FSM_TRIGGER_NETWORK_MENU,
    FSM_TRIGGER_SELECT_MENU,
    FSM_TRIGGER_SCREENSAVER
};

#endif