#pragma once

#define FLIPDOT_MAX_DATA 16
#define FLIPDOT_MAX_SIGN 16

#define FLIPDOT_PACKET_DATA_LEN_OFFSET 1
#define FLIPDOT_PACKET_DATA_LEN_LEN FLIPDOT_PACKET_DATA_LEN_OFFSET + 2
#define FLIPDOT_PACKET_SIGN_ADDRESS_OFFSET 3
#define FLIPDOT_PACKET_SIGN_ADDRESS_LEN FLIPDOT_PACKET_SIGN_ADDRESS_OFFSET + 4
#define FLIPDOT_PACKET_MSG_TYPE_OFFSET 7
#define FLIPDOT_PACKET_MSG_TYPE_LEN FLIPDOT_PACKET_MSG_TYPE_OFFSET + 2
#define FLIPDOT_PACKET_MSG_DATA_OFFSET 9
#define FLIPDOT_PACKET_CHECKSUM_OFFSET _rawFrameLen - 2
#define FLIPDOT_PACKET_CHECKSUM_LEN FLIPDOT_PACKET_CHECKSUM_OFFSET + 2

#define FLIPDOT_MSG_TYPE_SEND_DATA 0x00
#define FLIPDOT_MSG_TYPE_DATA_CHUNKS_SENT 0x01

#define FLIPDOT_DATA_PIXELS_COMPLETE 0x00

#define FLIPDOT_MSG_TYPE_BUS 0x02

#define FLIPDOT_BUS_QUERY_STATE 0x00
#define FLIPDOT_BUS_GOODBYE 0x55
#define FLIPDOT_BUS_DISCOVER 0xff

#define FLIPDOT_MSG_TYPE_REQUEST_OPERATION 0x03

#define FLIPDOT_OPS_REQUEST_RECEIVE_CONFIG 0xa1
#define FLIPDOT_OPS_REQUEST_RECEIVE_PIXELS 0xa2
#define FLIPDOT_OPS_REQUEST_START_RESET 0xa6
#define FLIPDOT_OPS_REQUEST_FINISH_RESET 0xa7
#define FLIPDOT_OPS_REQUEST_MORE_DATA 0xa8
#define FLIPDOT_OPS_REQUEST_SHOW_LOADED_PAGE 0xa9
#define FLIPDOT_OPS_REQUEST_LOAD_NEXT_PAGE 0xaa
#define FLIPDOT_OPS_REQUEST_NEXT_DATA 0xab

#define FLIPDOT_MSG_TYPE_REPORT_STATE 0x04

#define FLIPDOT_STATE_OK 0x00
#define FLIPDOT_STATE_SAVED 0x01
#define FLIPDOT_STATE_PIXELS_IN_PROGRESS 0x03
#define FLIPDOT_STATE_CONFIG_RECEIVED 0x07
#define FLIPDOT_STATE_READY_TO_RESET 0x08
#define FLIPDOT_STATE_PIXELS_FAILED 0x0b
#define FLIPDOT_STATE_CONFIG_FAILED 0x0c
#define FLIPDOT_STATE_CONFIG_IN_PROGRESS 0x0d
#define FLIPDOT_STATE_UNCONFIGURED 0x0f
#define FLIPDOT_STATE_PAGE_LOADED 0x10
#define FLIPDOT_STATE_PAGE_SHOW_IN_PROGRESS 0x11
#define FLIPDOT_STATE_PAGE_SHOWN 0x12
#define FLIPDOT_STATE_PAGE_LOAD_IN_PROGRESS 0x13

#define FLIPDOT_MSG_TYPE_ACK_OPERATION 0x05

#define FLIPDOT_ACK_RECEIVE_SIGN_CONFIG 0x63

#define FLIPDOT_ACK_RECEIVE_PIXELS 0x91
#define FLIPDOT_ACK_START_RESET 0x93
#define FLIPDOT_ACK_FINISH_RESET 0x94
#define FLIPDOT_ACK_RECEIVE_CONFIG 0x95
#define FLIPDOT_ACK_SHOW_LOADED_PAGE 0x95
#define FLIPDOT_ACK_LOAD_NEXT_PAGE 0x97

#define FLIPDOT_MSG_TYPE_PIXEL_COMPLETE 0x06

struct FlipDotPacket
{
    uint8_t msgType;
    uint8_t msgData[FLIPDOT_MAX_DATA];
    uint8_t msgDataLen;
};

typedef struct FlipDotPacket FlipDotPacket;

FlipDotPacket FlipDotPacket_Discovery = {.msgType = FLIPDOT_MSG_TYPE_BUS, .msgData = {FLIPDOT_BUS_DISCOVER}, .msgDataLen = 0x01};

FlipDotPacket FlipDotPacket_Goodbye = {.msgType = FLIPDOT_MSG_TYPE_BUS, .msgData = {FLIPDOT_BUS_GOODBYE}, .msgDataLen = 0x01};

FlipDotPacket FlipDotPacket_Query_State = {.msgType = FLIPDOT_MSG_TYPE_BUS, .msgData = {FLIPDOT_BUS_QUERY_STATE}, .msgDataLen = 0x01};

FlipDotPacket FlipDotPacket_Pixels_Complete = {.msgType = FLIPDOT_MSG_TYPE_PIXEL_COMPLETE, .msgData = {FLIPDOT_DATA_PIXELS_COMPLETE}, .msgDataLen = 0x01};